#!/usr/bin/env lua

local fs = require('fs')
local getopt = require('getopt')
local hash = require('hash')
local ipairs = ipairs
local mimetype = require('mimetype')
local pcall = pcall
local pairs = pairs
local os = os
local scgi = require('scgi')
local server = require('server')
local STATUS = scgi.STATUS
local string = string
local table = table
local tonumber = tonumber
local io = io

local USAGE = [[Usage: why [OPTION] document_root
A SCGI static file server

  -p The port to use (Default 8000)
  -v Print version and exit
  -h Show this message and exit]]

local VERSION = '1.0.0'

local function slurp(path)
  local file = io.open(path, 'rb')
  return file:read('*all')
end

local function endswith(str, needle)
  local suffix = str:sub(-(#needle))
  return suffix == needle
end

function table.merge(t1, t2, iter)
  local iter = iter or pairs
  for k, v in iter(t2) do
    t1[k] = v
  end
end

function table.contains(needle, haystack)
  for _, v in ipairs(haystack) do
    if v == needle then
      return true
    end
  end

  return false
end

local function process_request(request, files)
  local status, headers = pcall(scgi.parse_request, request)

  if not status then
    return scgi.build_response(STATUS.BAD_REQUEST), headers
  end

  local index = endswith(headers.REQUEST_URI, '/') and 'index.html' or ''
  local path = table.concat({headers.DOCUMENT_ROOT, headers.REQUEST_URI, index})

  if not files[path] then
    return scgi.build_response(STATUS.NOT_FOUND), 'Unknown file'
  end

  local file = files[path]
  local content = file.content
  local etag = file.etag

  local res_headers = {
    ['Content-Type'] = file.mime,
    ['Content-Length'] = file.length,
    ['ETag'] = etag
  }

  local none_match = headers.HTTP_IF_NONE_MATCH or ''
  if none_match == etag then
    return scgi.build_response(STATUS.NOT_MODIFIED, {['ETag'] = etag})
  end

  local accept_encoding = headers.HTTP_ACCEPT_ENCODING or {}
  for _, encoding in ipairs({'br', 'gzip'}) do
    if accept_encoding[encoding] and file[encoding] ~= nil then
      res_headers['Content-Encoding'] = encoding
      res_headers['Content-Length'] = file[encoding].length
      content = file[encoding].content
      break
    end
  end

  return scgi.build_response(STATUS.OK, res_headers), content
end

local function get_compressed_file(path)
  if not fs.exist(path) then
    return nil
  end

  local content = slurp(path)
  return {
    content = content,
    length = #content
  }
end

local function add_file(path, ext)
  local content = slurp(path)

  return {
    mime = mimetype.detect(ext),
    length = #content,
    content = content,
    etag = string.format("%x", hash.murmur(content)),
    gzip = get_compressed_file(path .. '.gz'),
    br = get_compressed_file(path .. '.br')
  }
end

local function get_files(dir)
  local files = {}

  if not endswith(dir, '/') then
    dir = dir .. '/'
  end

  for _, path in ipairs(fs.scandir(dir)) do
    if fs.is_dir(path) then
      table.merge(files, get_files(path))
    else
      local ext = fs.extname(path)

      if not table.contains(ext, {'.gz', '.br'}) then
        files[path] = add_file(path, ext)
      end
    end
  end

  return files
end

local function main()
  local opts, args = getopt.parse('vhp:')

  if opts.h or opts.v then
    print(opts.h and USAGE or VERSION)
    return
  end

  if not args[1] then
    print('Missing document root argument')
    print(USAGE)
    os.exit(1)
  end

  local document_root = args[1]
  local port = tonumber(opts.p) or 8000
  local files = get_files(document_root)
  local socket = server.bind(port)

  socket:accept(function(client)
    local headers, content = process_request(client:recv(), files)
    client:send(headers .. (content or ''))
  end)
end

main()

