#!/usr/bin/env lua

local fs = require('fs')
local getopt = require('getopt')
local hash = require('hash')
local io = io
local ipairs = ipairs
local mimetype = require('mimetype')
local pairs = pairs
local pcall = pcall
local print = print
local os = os
local scgi = require('scgi')
local server = require('server')
local STATUS = scgi.STATUS
local string = string
local table = table
local tonumber = tonumber

local magic = mimetype.open()

local COMMON_MIMETYPES = {
  ['.html'] = 'text/html',
  ['.htm'] = 'text/html',
  ['.css'] = 'text/css',
  ['.txt'] = 'text/plain',
  ['.jpg'] = 'image/jpeg',
  ['.jpeg'] = 'image/jpeg',
  ['.png'] = 'image/png',
  ['.gif'] = 'image/gif',
  ['.js'] = 'application/javascript'
}

local USAGE = [[Usage: why [OPTION] document_root
A SCGI static file server

  -p The port to use (Default 8000)
  -v Print version and exit
  -h Show this message and exit]]

local VERSION = '1.0.0'
local DEFAULT_PORT = 8000

local function throw(err)
  io.stderr:write(("%s: %s\n"):format(arg[0], err))
  os.exit(1)
end

local function slurp(path)
  local file = io.open(path, 'rb')
  return file:read('*all')
end

function string:endswith(ending)
  return self:sub(-#ending) == ending
end

function table.merge(t1, t2)
  for k, v in pairs(t2) do
    t1[k] = v
  end
end

function table.contains(needle, haystack)
  for _, v in ipairs(haystack) do
    if v == needle then
      return true
    end
  end

  return false
end

local function process_request(request, files)
  local ok, headers = pcall(scgi.parse_request, request)

  if not ok then
    return scgi.build_error_response(
      STATUS.BAD_REQUEST,
      'Server received an invalid request'
    )
  end

  local path = headers.DOCUMENT_ROOT .. headers.REQUEST_URI

  if not files[path] then
    return scgi.build_error_response(
      STATUS.NOT_FOUND,
      'The requested file doesn\'t exist'
    )
  end

  local file = files[path]
  local content = file.content
  local etag = file.etag
  local res_headers = {
    ['Content-Type'] = file.mime,
    ['Content-Length'] = file.length,
    ['ETag'] = etag
  }

  local none_match = headers.HTTP_IF_NONE_MATCH or ''

  if none_match == etag then
    return scgi.build_response(STATUS.NOT_MODIFIED, {['ETag'] = etag})
  end

  local accept_encoding = headers.HTTP_ACCEPT_ENCODING or {}

  for _, encoding in ipairs({'br', 'gzip'}) do
    if accept_encoding[encoding] and file[encoding] ~= nil then
      res_headers['Content-Encoding'] = encoding
      res_headers['Content-Length'] = file[encoding].length
      content = file[encoding].content
      break
    end
  end

  local response = scgi.build_response(STATUS.OK, res_headers)

  if headers.REQUEST_METHOD == 'HEAD' then
    return response
  end

  return response, content
end

local function get_compressed_file(path)
  if not fs.exist(path) then
    return nil
  end

  local content = slurp(path)
  return {
    content = content,
    length = #content
  }
end

local function add_file(path, ext)
  local content = slurp(path)

  return {
    mime = COMMON_MIMETYPES[ext] or magic:detect(path),
    length = #content,
    content = content,
    etag = ("%x"):format(hash.murmur(content)),
    gzip = get_compressed_file(path .. '.gz'),
    br = get_compressed_file(path .. '.br')
  }
end

local function get_files(dir)
  local files = {}

  if not dir:endswith('/') then
    dir = dir .. '/'
  end

  for _, path in ipairs(fs.scandir(dir)) do
    if fs.is_dir(path) then
      table.merge(files, get_files(path))
    else
      local basename, ext = fs.fnparts(path)

      if not table.contains(ext, {'.gz', '.br'}) then
        local file = add_file(path, ext)
        files[path] = file

        -- If we have an index file, alias the directory to it
        if basename == 'index.html' then
          files[dir] = file
        end
      end
    end
  end

  return files
end

local function serve(document_root, port)
  local files = get_files(document_root)

  print('Listening on port ' .. port)
  server.listen(port, function(client)
    local ok, headers, content = pcall(process_request, client:recv(), files)

    if not ok then
      local error_res = scgi.build_error_response(
        STATUS.INTERNAL_SERVER_ERROR,
        'Server encountered an error while processing the request'
      )
      client:send(error_res)
    else
      client:send(headers)

      if content then
        client:send(content)
      end
    end
  end)
end

local function main()
  local port = DEFAULT_PORT

  local args = getopt.parse('vhp:', function(opt, arg)
    if opt == 'h' then
      print(USAGE)
      os.exit()
    elseif opt == 'v' then
      print(VERSION)
      os.exit()
    elseif opt == 'p' then
      port = tonumber(arg)
      if not port or port < 0 then
        throw(('Invalid port provided (%s)'):format(arg))
      end
    end
  end)

  if not args[1] then
    throw([[Missing document root argument
Try 'why -h' for more information]])
  end

  local ok, err = pcall(serve, args[1], port)

  if not ok then
    throw(err)
  end
end

main()

